# Grab the build environment
Import('env')

obj_list = [env.yasm('loader.o', 'loader.asm')]
obj_list += [env.gdc('gdt.o', 'gdt.d')]
obj_list += [env.gdc('kernel.o', 'kernel.d')]

boot = env.PartialLink('boot.o', obj_list)

Return('boot')
