# Grab the build environment
Import('env')

if(env['target'] == 'i586'):
    obj_list  = [env.yasm('loader.o', 'loader.asm')]
else:
    obj_list = []

obj_list += [env.gdc('common.o',        'common.d')]
obj_list += [env.gdc('constants.o',     'constants.d')]
obj_list += [env.gdc('interrupts.o',    'interrupts.d')]
obj_list += [env.gdc('paging.o',        'paging.d')]
obj_list += [env.gdc('pic.o',           'pic.d')]
obj_list += [env.gdc('registers.o',     'registers.d')]
obj_list += [env.gdc('screen.o',        'screen.d')]
obj_list += [env.gdc('setup.o',         'setup.d')]
obj_list += [env.gdc('descriptors.o',   'descriptors.d')]

Return('obj_list')
