# Grab the build environment
Import('env')

obj_list = [env.gdc('kernel.o', 'kernel.d')]
obj_list += SConscript('boot/SConscript',         exports='env')
obj_list += SConscript('dev/SConscript',          exports='env')
obj_list += SConscript('mem/SConscript',          exports='env')
obj_list += SConscript('task/SConscript',         exports='env')

kernel = env.Link('kernel', obj_list, LINKSCRIPTS = ['kernel/link/linker.ld'], _LIBDIRFLAGS = '-Lneptune -Ltriton', _LIBFLAGS = '-lneptune -lgphobos')

Return('kernel')
