# Grab the build environment
Import('env', 'lib')

obj_list  = SConscript('boot/SConscript', exports='env')
obj_list += SConscript('core/SConscript', exports='env')
obj_list += SConscript('dev/SConscript',  exports='env')
obj_list += SConscript('mem/SConscript',  exports='env')
obj_list += SConscript('task/SConscript',  exports='env')

kernel = env.Link('kernel', obj_list + lib['util'] + lib['triton'], LINKSCRIPTS = ['kernel/link/linker.ld'])

Return('kernel')
