# Grab the build environment
Import('env')

obj_list  = [env.gdc('Arch.o', 'Arch.d')]
obj_list += [env.gdc('Descriptor.o', 'Descriptor.d')]
obj_list += [env.gdc('GDT.o', 'GDT.d')]
obj_list += [env.gdc('IDT.o', 'IDT.d')]
obj_list += [env.yasm('interrupts.o', 'interrupts.asm')]
obj_list += [env.gdc('PageTable.o', 'PageTable.d')]
obj_list += [env.gdc('TSS.o', 'TSS.d')]

Return('obj_list')
