# Grab the build environment
Import('env')

obj_list  = [env.gdc('bitarray.o', 'bitarray.d')]
obj_list += [env.gdc('intrinsic.o', 'intrinsic.d')]
obj_list += [env.gdc('stdarg.o', 'stdarg.d')]
obj_list += SConscript('typeinfo/SConscript', exports='env')

Return('obj_list')
