# Grab the build environment

Import('env', 'lib')

# Build object files
obj_list  = [env.yasm('loader.o', 'loader.asm')]
obj_list += [env.gdc('host.o', 'host.d')]
obj_list += [env.gdc('main.o', 'main.d')]

# Build the loader
loader = env.Link('loader', obj_list + lib['util'] + lib['triton'], LINKSCRIPTS = [env.File('linker.ld')])

Return('loader')
