# Grab the build environment
Import('env')

obj_list = [env.gdc('Screen.o', 'Screen.d')]
obj_list += [env.gdc('Keyboard.o', 'Keyboard.d')]
obj_list += [env.gdc('Mouse.o', 'Mouse.d')]

Return('obj_list')
