# Grab the build environment

Import('i586_env')
env = i586_env

# Set up build flags
env['CXXFLAGS']  += ['-fno-exceptions']
#env['LINKFLAGS'] += ['-nostdlib',
#                     '-nostartfiles',
#                     '-nodefaultlibs']

# Build object files
obj_list  = [env.yasm('start.o', 'start.asm')]
obj_list += [env.gdc('loader.o', 'loader.d')]

# Build the loader
loader = env.Link('loader', obj_list, LINKSCRIPTS=[env.File('linker.ld')])

Return('loader')
