# Grab the build environment
Import('x86_64_env')
env    = x86_64_env

obj_list  = [env.gdc('arraycat.o', 'arraycat.d')]
obj_list += [env.gdc('cast.o', 'cast.d')]
obj_list += [env.gdc('error.o', 'error.d')]
obj_list += [env.gdc('genobj.o', 'genobj.d')]
obj_list += [env.gdc('invariant.o', 'invariant.d')]
obj_list += [env.gdc('lifetime.o', 'lifetime.d')]

Return('obj_list')
